### ISSUE TITLE
Migrate to PAT 2.0

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BuildStock#43]
PAT 2.0 development to support ResStock
- [x] Use of docker & OS 2.0 (will fix #12 and #38)
- [x] Implementation of diagonal sampling
- [x] Cannot specify integer_sequence distribution for pivot variable
- [x] `number_of_samples` not available in the runner
- [x] Allowing measures to be brought into the project multiple times (to be used with different arguments)
- [x] Use results CSV for project reporting measures in algorithmic mode
- [x] Allow relative path for resources so PAT project can be easily shared
- [x] Unable to download large SQL output files
- [x] [Can't run new laptop on AWS ](https://github.com/NREL/OpenStudio/issues/2558)
- [x] Can't run national project -- zip too large? (Moved weather files to s3 bucket zip file downloaded by worker init script)
- [x] Integer sequence [error running the analysis](https://github.com/NREL/OpenStudio/issues/2583)
- [x] [Bug when duplicating ApplyUpgrade measure](https://github.com/NREL/OpenStudio/issues/2565)
- [x] Implementation of datapoint initialization/finalization scripts
- [x] Ability to skip N/A simulations (#37)
- [ ] Implementation of server initialization/finalization scripts

ResStock development
- [x] Create PAT 2.0 project
- [x] Switch from use of `runner.past_results` to `results.step`
- [x] Add outputs to PAT project (and reporting measures where possible)
- [x] Use relative paths as appropriate
- [x] Check if DDYs are being sent to the server
- [x] Fix weight calculation (use integer_sequence max value rather than algorithm number_of_samples)
- [x]  Use s3 bucket & init script for weather files
- [x] Hook up sampling as datapoint init script
- [x] Clean out datapoint dirs as datapoint final script
- [x] Fix output variables as needed (once OS 2.2 is out)
- [x] Add option name argument to ApplyUpgrade measure since there is nowhere else to store this in PAT? ([PAT feature request](https://github.com/NREL/OpenStudio/issues/2571))
- [ ] Hook up post-processing server final script

cc @ejhw @joseph-robertson

**Comment by shorowit** [comment]
Essentially complete! I'll open a separate ticket specifically related to the server init/final scripts.
